In [1]:
#1. Write a Python Program to find sum of array?

import numpy
def add_array(l,l1):
    """add the array"""
    arr = numpy.array(l)
    arr1 = numpy.array(l1)
    return arr + arr1

arr = eval(input("enter the list or nested list "))
arr1 = eval(input("enter the list or nested list "))

add_array(arr,arr1)

enter the list or nested list [[1,2,3,4],[1,3,2,4]]
enter the list or nested list [[1,2,3,4],[1,2,3,4]]


array([[2, 4, 6, 8],
       [2, 5, 5, 8]])

In [2]:
#2. Write a Python Program to find largest element in an array?

import numpy
def largest_array(l):
    """add the array"""
    arr1 = numpy.array(l)
    return numpy.max(arr)

arr = eval(input("enter the list or nested list "))
largest_array(arr)

enter the list or nested list [[1,2,3,4],[1,2,3,4]]


4

In [3]:
#3.Write a Python Program for array rotation?

import numpy
def rotate_array(l):
    """rotate the array"""
    
    arr1 = numpy.array(l)
    shape = (arr1.shape[1],arr1.shape[0])
    new_arr = numpy.empty(shape)
    for i in range(arr1.shape[1]):
        for j in range(arr1.shape[0]-1,-1,-1):
            new_arr[i,j-1]=arr1[j,i]
    return new_arr
    

arr = eval(input("enter the nested list "))
rotate_array(arr)

enter the nested list [[1,2,3,4],[1,2,3,4]]


array([[1., 1.],
       [2., 2.],
       [3., 3.],
       [4., 4.]])

In [4]:
#4.Write a Python Program to split the array and add the first part to the end?

def first_at_end(l):
    k = int(input("enter the index "))
    arr = numpy.array(l)
    for i in range(k):
        x = arr[0]
        for j in range(len(arr)-1):
            arr[j] = arr[j+1]
        arr[j+1]=x
    return arr
    
arr = eval(input("enter the list "))
first_at_end(arr)

enter the list [1,2,3,4]
enter the index 2


array([3, 4, 1, 2])

In [21]:
#5. Write a Python Program to check if given array is Monotonic?

arr=eval(input())
a=numpy.array(arr)
def monotonic(arr):
    return all(arr[i]<=arr[i+1]  for i in range(len(arr)-1)) or all( arr[i]>=arr[i+1]for i in range(len(arr)-1))
monotonic(a)

[1,2,3,4]


True