In [1]:
#1. Write a Python Program to Add Two Matrices?
import numpy as np
    
try:
    def add(n,m):
        if type(n) == list and type(m) == list:
            mat1 = np.matrix(n)
            mat2 = np.matrix(m)
            add = np.zeros(mat1.shape)
            add = mat1 + mat2
        return add

    n=eval(input('enter the list or nested list mat1 '))
    m=eval(input('enter the list or nested list mat2 '))
    total = add(n,m)
    print(total)
except Exception as e:
    print(e)

enter the list or nested list mat1 [[1,2,3],[4,5,6]]
enter the list or nested list mat2 [[2,3,4],[3,5,4]]
[[ 3  5  7]
 [ 7 10 10]]


In [7]:
#2. Write a Python Program to Multiply Two Matrices?
import numpy as np
    
try:
    def mult(n,m):
        if type(n) == list and type(m) == list:
            mat1 = np.matrix(n)
            mat2 = np.matrix(m)
            if mat1.shape[1]==mat2.shape[0]:
                multiply = np.zeros((mat1.shape[1],mat2.shape[0]))
                multiply = mat1 * mat2
                return multiply
            else:
                return "getting some error"

    n=eval(input('enter the list or nested list mat1 '))
    m=eval(input('enter the list or nested list mat2 '))
    total = mult(n,m)
    print(total)
except Exception as e:
    print(e)

enter the list or nested list mat1 [[1,3,4],[1,3,4]]
enter the list or nested list mat2 [[1,2,4],[2,4,5],[2,4,5]]
[[15 30 39]
 [15 30 39]]


In [8]:
#3. Write a Python Program to Transpose a Matrix?
import numpy as np
    
try:
    def trans(n):
        mat1 = np.matrix(n)
        trans = np.zeros((mat1.shape[1],mat1.shape[0]))
        for i in range(mat1.shape[0]):
            trans[:,i] = mat1[i,:]
        return trans[:,:]
    n=eval(input('enter the list or nested list mat1 '))
    total = trans(n)
    print(total)
except Exception as e:
    print(e)

enter the list or nested list mat1 [[2,3,5],[2,3,4]]
[[2. 2.]
 [3. 3.]
 [5. 4.]]


In [18]:
#4. Write a Python Program to Sort Words in Alphabetic Order?
def sort(n):
    s = n.split()
    s.sort()
    return ' '.join(s)
n = input()
w = sort(n)
print(w)

Python Programming Basic Assignment_5
Assignment_5 Basic Programming Python


In [19]:
# 5. Write a Python Program to Remove Punctuation From a String?
import string
def punctutation(n):
    str = ""
    for i in n:
        if i not in string.punctuation:
            str = str + i
    return str
n = input()
punctutation(n)

Pyt#$%h^&*on Programming Ba#&sic Ass#$^ignment_5


'Python Programming Basic Assignment5'